
spring:
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/tams?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10

logging:
  level:
    com.lhd.tams: info

springdoc:
  api-docs:
    enabled: false

tams:
  logging:
    path: /logs/tams/logs
